/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResponsibleAdvertisingRouteImport } from './routes/responsible-advertising'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies/index'
import { Route as GuidesTiktokAdsCloakingRouteImport } from './routes/guides/tiktok-ads-cloaking'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies/$slug'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAdvertisingRoute = ResponsibleAdvertisingRouteImport.update({
  id: '/responsible-advertising',
  path: '/responsible-advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesTiktokAdsCloakingRoute = GuidesTiktokAdsCloakingRouteImport.update({
  id: '/guides/tiktok-ads-cloaking',
  path: '/guides/tiktok-ads-cloaking',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/markets': typeof MarketsRoute
  '/playbook': typeof PlaybookRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/responsible-advertising': typeof ResponsibleAdvertisingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/guides/tiktok-ads-cloaking': typeof GuidesTiktokAdsCloakingRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/markets': typeof MarketsRoute
  '/playbook': typeof PlaybookRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/responsible-advertising': typeof ResponsibleAdvertisingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/guides/tiktok-ads-cloaking': typeof GuidesTiktokAdsCloakingRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/markets': typeof MarketsRoute
  '/playbook': typeof PlaybookRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/responsible-advertising': typeof ResponsibleAdvertisingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/guides/tiktok-ads-cloaking': typeof GuidesTiktokAdsCloakingRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/markets'
    | '/playbook'
    | '/privacy'
    | '/proof'
    | '/responsible-advertising'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/reviews'
    | '/case-studies/$slug'
    | '/guides/tiktok-ads-cloaking'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/markets'
    | '/playbook'
    | '/privacy'
    | '/proof'
    | '/responsible-advertising'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/reviews'
    | '/case-studies/$slug'
    | '/guides/tiktok-ads-cloaking'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/markets'
    | '/playbook'
    | '/privacy'
    | '/proof'
    | '/responsible-advertising'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/reviews'
    | '/case-studies/$slug'
    | '/guides/tiktok-ads-cloaking'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  MarketsRoute: typeof MarketsRoute
  PlaybookRoute: typeof PlaybookRoute
  PrivacyRoute: typeof PrivacyRoute
  ProofRoute: typeof ProofRoute
  ResponsibleAdvertisingRoute: typeof ResponsibleAdvertisingRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  GuidesTiktokAdsCloakingRoute: typeof GuidesTiktokAdsCloakingRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-advertising': {
      id: '/responsible-advertising'
      path: '/responsible-advertising'
      fullPath: '/responsible-advertising'
      preLoaderRoute: typeof ResponsibleAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/tiktok-ads-cloaking': {
      id: '/guides/tiktok-ads-cloaking'
      path: '/guides/tiktok-ads-cloaking'
      fullPath: '/guides/tiktok-ads-cloaking'
      preLoaderRoute: typeof GuidesTiktokAdsCloakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  MarketsRoute: MarketsRoute,
  PlaybookRoute: PlaybookRoute,
  PrivacyRoute: PrivacyRoute,
  ProofRoute: ProofRoute,
  ResponsibleAdvertisingRoute: ResponsibleAdvertisingRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  GuidesTiktokAdsCloakingRoute: GuidesTiktokAdsCloakingRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
